### ISSUE TITLE
summary of GSOC calls

### ISSUE THREAD

**Issue by tdhock** [diego-urgell/BinSeg#2]
- template vs subclass for generic loss functions
- generation of docs via roxygen2
- TODOS for next week: investigate if current approach is a good idea with binary segmentation + change in mean loss.
- set.seed(1) to control random numbers (if you use random numbers for input data)

**Comment by tdhock** [comment]
@diego-urgell during the next call please try to take notes and write them as a new comment in this issue.
yesterday we discussed the new registration in C++ code, and next steps implementing binseg for normal change in mean.

**Comment by tdhock** [comment]
- implement binary segmentation algorithm, change in mean and constant variance
- more challenging than anticipated. run-time off by one errors.
- summary statistics parent class for cumsum and cumsumsquared
- figure out a way to get summary statistics as a static member of distributions? it can be determined at compile time (does not change at run time)
- compilation warnings #4 
- add 1 to indices in RcppInterface.cpp before returning to R.
- error handling, number of changepoints too large? invalid distribution or algorithm?
- use tests/testthat/test-*.R files if you want to use devtools::test()
- goals for next week, more test cases for bin seg change in mean. loss and segment mean values. different cost functions. multiple parameter return, change NumericVector before_mean,after_mean to NumericMatrix before_params,after_params
- reading: good intro to ML / stats https://web.stanford.edu/~hastie/ElemStatLearn/

**Comment by diego-urgell** [comment]
Review: 
 
- Implemented cost function for Normal change in variance and Normal change in mean and variance 
- Added minSegLen constraint and a mechanism to avoid zero variance segmentation 
- Implemented a mechanism to dynamically create a numeric matrix that contains the necessary parameters, by creating virtual methods and overloading them on each distribution
- Tested the current functions using `changepoint`

Next Week: 

- Create more tests with the three existing distributions (Normal). Use the `changepoint` package for now. 
- Decide and implement a way to determine the cost of each segment from the R interface. 
- Set up codecov along with `covr` for code coverage analysis. 
- Implement more distributions and start testing them. 
- GSOC mid-term evaluations.

**Comment by diego-urgell** [comment]
**TODOS for next week:**
- [x] Correct implementation of Poisson cost function by using MLE for the rate parameter. 
- [x] Implement the cost function for the Exponential distribution 
- [x] Ask @tdhock about the differences in Negative Binomial cost function and rate parameter estimation between BinSeg and gfpop
- [x] Implement the structure of the S4 class for the user interface
- [ ] Set up the coef method to build segmentation models of a particular number of change points

**Comment by diego-urgell** [comment]
TODOS for this week: 

- [x] Implement coef method 
- [x] Implement graph method
- [x] Implement resid method
- [x] Finish the user-facing methods and the BinSeg class
- [ ] Correct the poisson and exponential cost functions (reduce computing cost)
- [ ] Include the missing parts of the log likelihood equation in R code. Achieve `-2*logLik`for every distribution. 
- [X] Start writing the user documentation.

**Comment by rkillick** [comment]
Looks like a challenge for this week. Just a quick note that there is no "graph" generic, it is plot.

**Comment by diego-urgell** [comment]
@rkillick It is definitely a challenge! I worked a lot on the R interface and it is almost complete, in PR #9 

After this I will write documentation for the functions :)

**Comment by diego-urgell** [comment]
TODOS for this week

- [X] Finish the documentation 
- [ ] Correct the poisson and exponential cost functions (reduce computing cost)
- [ ]  Include the missing parts of the log likelihood equation in R code. Achieve -2*logLikfor every distribution.
- [x] Make sure the package passes all CRAN checks
- [x] Place static expected result on tests 
- [ ] Look at Wild Binary Segmentation paper. Start thinking/planning about the implementation

**Comment by diego-urgell** [comment]
TODOS for this week: 

- [x] Correct the poisson and exponential cost functions (reduce computing cost)
- [x] Include the missing parts of the log likelihood equation in R code. Achieve -2*logLik for every distribution except negbin.
- [x] Add tests for the R interface methods
- [x] Check the resid function 
- [x] Write a Readme for the Github repository 
- [x] Set contributions in Description File
- [x] Setup release for final submission

**Comment by diego-urgell** [comment]
Hi @rkillick and @tdhock! I finished everything for the final submission! I created a README that has information about the package, and a report on GSOC 2021 at the end. Does it look good?

**Comment by tdhock** [comment]
yes good job
